### ISSUE TITLE
Version check did not catch non-following version

### ISSUE THREAD

**Issue by jakobbraun** [exasol/release-droid#207]
I accidentally released a version 0.3.0 of https://github.com/exasol/ci-isolation-aws directly after 0.1.1.
Usually release-droid prohibits this during release.
Maybe one reason why it didn't was, that there existes a `changes_0.2.0.md` file in the repo. However, the file does not have a release date and was never released.

**Comment by AnastasiiaSergienko** [comment]
The previous release check is based on the GitHub releases list I get from GitHub API. When you released 0.3.0 the previous one was pre-release 0.1.1 and GitHub API doesn't count it a release, so the list of releases was empty, and release droid assumed that you're doing the first release on the repo. And for the first release, we have allowed using any version, probably also because of the pre-releases you're doing sometimes. I recommend not using pre-releasing to avoid this problem.

**Comment by jakobbraun** [comment]
Ok, thanks for the clarification
