### ISSUE TITLE
Add support for Maven projects with multiple modules

### ISSUE THREAD

**Issue by kaklakariada** [exasol/release-droid#228]
Maven projects with multiple modules like [project-keeper](https://github.com/exasol/project-keeper) are currently not supported by release-droid.

Currently for project-keeper release-droid issues the follwing messages
*    Project URL is missing in the pom.xml file. [For platforms: MAVEN]
*    Project description is missing in the pom.xml file. [For platforms: MAVEN]
*    E-RD-REP-15: Required maven plugin is missing: 'project-keeper-maven-plugin'. [For platforms: MAVEN,GITHUB]

Hint:
Combine with #243

**Comment by ckunki** [comment]
Release to githup is implemented in `release_droid_upload_github_release_assets.yml`
```
shogo82148/actions-upload-release-asset@v1
```
Initial hypothesis: Could also work for multi-module maven projects.

**Comment by ckunki** [comment]
In discussions with @kaklakariada and @redcatbear we decided to remove the validation for project-keeper-maven-plugin to be used in pom. 
Rationale
* release-droid only validates, that the plugin is used but does not use the plugin itself
* requirement `req~releasing-on-maven~1` only requires to be able to release on maven, not to validate specific plugins 
* `design.md` covers `req~releasing-on-maven~1` in other ways, anyway 
* technically project-keeper-maven-plugin is not required, much more the workflow files must exist, which is covered by design, impl and test, anyway 
* potentially there are more projects to be published, but not using project-keeper-maven-plugin
