### ISSUE TITLE
Validate Project-Keeper file

### ISSUE THREAD

**Issue by redcatbear** [exasol/release-droid#273]
## Situation

I had a MC release with Release Droid where the item `- maven central` was missing in the section `sources:modules:` in the `.project-keeper` file. This led to a half-backed release where files were missing and that caused the MC release to silently fail.

## Acceptance criteria

* Validate that the modules in `.project-keeper` file (if present) match the release settings of RD

**Comment by ckunki** [comment]
Hi @redcatbear I understand the issue, however I propose to change PK rather than RD. Why? Because from a process perspective PK is able to detect, report and enable developer to fix issues much earlier. See also https://github.com/exasol/project-keeper/issues/389, and #240.
When RD comes into play it's too late from my perspective and RD can only refuse to release while PK usually runs before merging a PR. 

If you do not have any objections, I will move the ticket to PK, OK?

**Comment by ckunki** [comment]
Feedback from @redcatbear: Change in RD is still required for projects not using PK.
Optimum solution would be to add a change to RD first and second (for convenience) to PK, as well. 
So current issue #273 stay where it is and for PK see issue <TBD>.

**Comment by ckunki** [comment]
After additional review @redcatbear  and me came to the following conclusion
* check by PK is more important, earlier and more helpful
* check by RD is then no longer required 
* In projects not using PK the inconsistency described in the current ticket cannot happen.

Closing ticket.
